#ifndef NANOBOT_WWW_INDEX_H
#define NANOBOT_WWW_INDEX_H
static const char WWW_INDEX_HTML[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "<meta charset=\"utf-8\"/>\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\"/>\n"
  "<title>nanobot</title>\n"
  "<style>\n"
  ":root{\n"
  "  color-scheme:dark;\n"
  "  --bg:#0a0e12; --panel:#11181e; --fg:#e8eef2; --mut:#7a8a94;\n"
  "  --acc:#00e5ff; --ok:#3ddc97; --warn:#ffb020; --bad:#ff6b6b;\n"
  "  --line:#1c262c; --tab:#151c22;\n"
  "}\n"
  "*{box-sizing:border-box}\n"
  "html,body{margin:0;height:100%;background:var(--bg);color:var(--fg);\n"
  "  font:14px/1.4 system-ui,-apple-system,Segoe UI,sans-serif}\n"
  "#app{display:flex;flex-direction:column;height:100%;max-width:42rem;margin:0 auto}\n"
  "header{display:flex;align-items:center;justify-content:space-between;gap:.5rem;\n"
  "  padding:.55rem .75rem;border-bottom:1px solid var(--line);background:var(--panel)}\n"
  "header .brand{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13px;color:var(--mut)}\n"
  "header .brand b{color:var(--acc);font-weight:700}\n"
  "#status{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:11px;color:var(--mut);\n"
  "  max-width:55%;text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
  "#status .ok{color:var(--ok)} #status .warn{color:var(--warn)}\n"
  "nav.tabs{display:flex;gap:0;border-bottom:1px solid var(--line);background:var(--tab)}\n"
  "nav.tabs button{flex:1;border:0;background:transparent;color:var(--mut);font:inherit;font-weight:600;\n"
  "  padding:.65rem .5rem;cursor:pointer;border-bottom:2px solid transparent}\n"
  "nav.tabs button.on{color:var(--acc);border-bottom-color:var(--acc)}\n"
  "main{flex:1;min-height:0;display:flex;flex-direction:column}\n"
  ".page{display:none;flex-direction:column;flex:1;min-height:0;padding:.65rem .75rem}\n"
  ".page.on{display:flex}\n"
  "/* chat */\n"
  "#log{flex:1;overflow:auto;font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13px;\n"
  "  white-space:pre-wrap;word-break:break-word;padding:.25rem 0 .5rem}\n"
  ".u{color:var(--acc)} .a{color:var(--fg)} .s{color:var(--mut)} .err{color:var(--bad)}\n"
  "#composer{display:flex;gap:.4rem;border-top:1px solid var(--line);padding-top:.5rem}\n"
  "#q{flex:1;min-width:0;background:var(--panel);color:var(--fg);border:1px solid var(--line);\n"
  "  border-radius:8px;padding:.7rem .75rem;font:inherit;outline:none}\n"
  "#q:focus{border-color:var(--acc)}\n"
  "#go{background:var(--acc);color:#00343a;border:0;border-radius:8px;padding:0 1rem;\n"
  "  font:inherit;font-weight:700;cursor:pointer;min-width:3.75rem}\n"
  "#go:disabled{opacity:.5;cursor:wait}\n"
  "#hint{font-size:11px;color:var(--mut);padding:.35rem 0 0;font-family:ui-monospace,Menlo,Consolas,monospace}\n"
  "/* settings */\n"
  ".card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:.85rem;margin:0 0 .65rem}\n"
  ".card h2{margin:0 0 .55rem;font-size:.72rem;color:var(--mut);text-transform:uppercase;\n"
  "  letter-spacing:.06em;font-weight:700}\n"
  ".field{margin:0 0 .55rem}\n"
  ".field label{display:block;font-size:12px;color:var(--mut);margin:0 0 .25rem}\n"
  ".field input,.field select{width:100%;background:var(--bg);color:var(--fg);border:1px solid var(--line);\n"
  "  border-radius:8px;padding:.55rem .65rem;font:inherit}\n"
  ".field .note{font-size:11px;color:var(--mut);margin-top:.25rem}\n"
  ".row{display:flex;flex-wrap:wrap;gap:.4rem;margin-top:.35rem}\n"
  "button.btn,a.btn{appearance:none;border:1px solid var(--line);background:#1a2228;color:var(--fg);\n"
  "  border-radius:8px;padding:.55rem .85rem;font:inherit;font-weight:600;cursor:pointer;text-decoration:none}\n"
  "button.btn.primary,a.btn.primary{background:var(--acc);color:#00343a;border-color:transparent}\n"
  "button.btn.ghost{background:transparent;color:var(--acc);border-color:var(--acc)}\n"
  "button.btn:disabled{opacity:.5;cursor:wait}\n"
  "#auth-box{display:none;margin-top:.55rem;padding:.65rem;border:1px dashed var(--line);border-radius:8px}\n"
  "#auth-box.show{display:block}\n"
  "#auth-box .code{color:var(--acc);font-family:ui-monospace,Menlo,Consolas,monospace;\n"
  "  letter-spacing:.12em;font-size:1.15rem;margin:.3rem 0}\n"
  "#auth-box a{color:var(--acc);word-break:break-all;font-size:12px}\n"
  "#auth-box .meta{font-size:12px;color:var(--mut);margin-top:.35rem}\n"
  ".kv{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:12px;color:var(--fg)}\n"
  ".kv span{color:var(--mut)}\n"
  ".foot{font-size:10px;color:var(--mut);margin-top:.5rem;line-height:1.35}\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"app\">\n"
  "  <header>\n"
  "    <div class=\"brand\"><b>nanobot</b> · dashboard</div>\n"
  "    <div id=\"status\">…</div>\n"
  "  </header>\n"
  "  <nav class=\"tabs\" role=\"tablist\">\n"
  "    <button type=\"button\" class=\"on\" data-tab=\"chat\" role=\"tab\" aria-selected=\"true\">Chat</button>\n"
  "    <button type=\"button\" data-tab=\"settings\" role=\"tab\" aria-selected=\"false\">Settings</button>\n"
  "  </nav>\n"
  "  <main>\n"
  "    <!-- CHAT -->\n"
  "    <section id=\"page-chat\" class=\"page on\" role=\"tabpanel\">\n"
  "      <div id=\"log\" aria-live=\"polite\"></div>\n"
  "      <div id=\"composer\">\n"
  "        <input id=\"q\" type=\"text\" autocomplete=\"off\" autocorrect=\"off\" spellcheck=\"false\"\n"
  "          placeholder=\"Message · @! shell · help\" maxlength=\"2000\" autofocus/>\n"
  "        <button id=\"go\" type=\"button\">Go</button>\n"
  "      </div>\n"
  "      <div id=\"hint\">@! cmd · help · /s · /log · /clear · Settings → backend &amp; Connect Grok</div>\n"
  "    </section>\n"
  "\n"
  "    <!-- SETTINGS -->\n"
  "    <section id=\"page-settings\" class=\"page\" role=\"tabpanel\" hidden>\n"
  "      <div class=\"card\">\n"
  "        <h2>LLM backend</h2>\n"
  "        <div class=\"field\">\n"
  "          <label for=\"be\">Mode</label>\n"
  "          <select id=\"be\">\n"
  "            <option value=\"grok\">Grok (cloud)</option>\n"
  "            <option value=\"local\">Local — llama.cpp / OpenAI-compatible</option>\n"
  "          </select>\n"
  "          <div class=\"note\">Outer host (UI, shell, memory) stays the same; only the model endpoint changes.</div>\n"
  "        </div>\n"
  "        <div id=\"local-fields\">\n"
  "          <div class=\"field\">\n"
  "            <label for=\"base\">Base URL</label>\n"
  "            <input id=\"base\" type=\"text\" spellcheck=\"false\" placeholder=\"http://127.0.0.1:8080/v1\"/>\n"
  "          </div>\n"
  "          <div class=\"field\">\n"
  "            <label for=\"model\">Model id</label>\n"
  "            <input id=\"model\" type=\"text\" spellcheck=\"false\" placeholder=\"local or model name\"/>\n"
  "          </div>\n"
  "        </div>\n"
  "        <div class=\"row\">\n"
  "          <button type=\"button\" class=\"btn primary\" id=\"btn-apply\">Apply backend</button>\n"
  "          <button type=\"button\" class=\"btn ghost\" id=\"btn-refresh\">Refresh status</button>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <div class=\"card\">\n"
  "        <h2>Grok connection</h2>\n"
  "        <p class=\"note\" style=\"margin:0 0 .5rem;color:var(--mut);font-size:12px\">\n"
  "          Device-code login. nanobot generates a link; you authorize in a normal browser — no API keys stored by you.\n"
  "          Unofficial; not affiliated with xAI/Grok.\n"
  "        </p>\n"
  "        <div class=\"row\">\n"
  "          <button type=\"button\" class=\"btn primary\" id=\"btn-connect\">Connect Grok</button>\n"
  "          <button type=\"button\" class=\"btn\" id=\"btn-activate\">Open /activate</button>\n"
  "        </div>\n"
  "        <div id=\"auth-box\">\n"
  "          <div class=\"meta\">User code</div>\n"
  "          <div class=\"code\" id=\"code\">—</div>\n"
  "          <div class=\"meta\">Activation link</div>\n"
  "          <div><a id=\"act\" href=\"#\" target=\"_blank\" rel=\"noopener\">—</a></div>\n"
  "          <div class=\"meta\" id=\"wait\">Waiting for browser approval…</div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <div class=\"card\">\n"
  "        <h2>Status</h2>\n"
  "        <div class=\"kv\" id=\"status-detail\">loading…</div>\n"
  "        <div class=\"foot\">Session &amp; settings live under NANOBOT_HOME (env file). @! shell works without any model.</div>\n"
  "      </div>\n"
  "    </section>\n"
  "  </main>\n"
  "</div>\n"
  "<script>\n"
  "const $ = id => document.getElementById(id);\n"
  "const logEl = $('log'), q = $('q'), go = $('go'), statusEl = $('status');\n"
  "const be = $('be'), base = $('base'), model = $('model'), localFields = $('local-fields');\n"
  "const authBox = $('auth-box'), act = $('act'), codeEl = $('code'), waitEl = $('wait');\n"
  "const statusDetail = $('status-detail');\n"
  "let pollTimer = null;\n"
  "let lastAuth = null;\n"
  "\n"
  "function add(cls, t){\n"
  "  const d = document.createElement('div');\n"
  "  d.className = cls;\n"
  "  d.textContent = t;\n"
  "  logEl.appendChild(d);\n"
  "  logEl.scrollTop = logEl.scrollHeight;\n"
  "}\n"
  "\n"
  "function showTab(name){\n"
  "  document.querySelectorAll('nav.tabs button').forEach(b=>{\n"
  "    const on = b.dataset.tab === name;\n"
  "    b.classList.toggle('on', on);\n"
  "    b.setAttribute('aria-selected', on ? 'true' : 'false');\n"
  "  });\n"
  "  document.querySelectorAll('.page').forEach(p=>{\n"
  "    const on = p.id === 'page-'+name;\n"
  "    p.classList.toggle('on', on);\n"
  "    p.hidden = !on;\n"
  "  });\n"
  "  if (name === 'chat') q.focus();\n"
  "}\n"
  "\n"
  "document.querySelectorAll('nav.tabs button').forEach(b=>{\n"
  "  b.onclick = () => showTab(b.dataset.tab);\n"
  "});\n"
  "\n"
  "function syncLocalFields(){\n"
  "  localFields.style.display = be.value === 'local' ? 'block' : 'none';\n"
  "}\n"
  "be.onchange = syncLocalFields;\n"
  "\n"
  "function paintStatus(j){\n"
  "  lastAuth = j;\n"
  "  const local = j.needs_browser === false || j.backend === 'openai_compatible';\n"
  "  const signed = !!j.signed_in;\n"
  "  if (local) {\n"
  "    statusEl.innerHTML = '<span class=\"ok\">local</span> · '+(j.model||'');\n"
  "  } else if (signed) {\n"
  "    statusEl.innerHTML = '<span class=\"ok\">grok✓</span> · '+(j.model||'');\n"
  "  } else {\n"
  "    statusEl.innerHTML = '<span class=\"warn\">grok · connect</span>';\n"
  "  }\n"
  "  be.value = local ? 'local' : 'grok';\n"
  "  if (j.base_url) base.value = j.base_url;\n"
  "  if (j.model) model.value = j.model;\n"
  "  syncLocalFields();\n"
  "\n"
  "  statusDetail.innerHTML =\n"
  "    '<div><span>backend</span> '+(j.backend||'?')+'</div>'+\n"
  "    '<div><span>base</span> '+(j.base_url||'?')+'</div>'+\n"
  "    '<div><span>model</span> '+(j.model||'?')+'</div>'+\n"
  "    '<div><span>signed_in</span> '+(j.signed_in?'yes':'no')+'</div>'+\n"
  "    '<div><span>auth</span> '+(j.auth||'?')+'</div>'+\n"
  "    '<div><span>home</span> '+(j.workdir||'?')+'</div>';\n"
  "\n"
  "  const u = j.verification_uri_complete || j.verification_uri;\n"
  "  if (u && !signed && !local) {\n"
  "    act.href = u;\n"
  "    act.textContent = u;\n"
  "    if (j.user_code) codeEl.textContent = j.user_code;\n"
  "    authBox.classList.add('show');\n"
  "  } else if (signed || local) {\n"
  "    authBox.classList.remove('show');\n"
  "  }\n"
  "  return signed || local;\n"
  "}\n"
  "\n"
  "async function refreshAuth(){\n"
  "  try {\n"
  "    const r = await fetch('/api/auth');\n"
  "    const j = await r.json();\n"
  "    return paintStatus(j);\n"
  "  } catch (e) {\n"
  "    statusEl.textContent = 'offline';\n"
  "    return false;\n"
  "  }\n"
  "}\n"
  "\n"
  "async function applyBackend(){\n"
  "  const body = be.value === 'local'\n"
  "    ? { backend:'local', base_url: (base.value||'').trim()||'http://127.0.0.1:8080/v1',\n"
  "        model: (model.value||'').trim()||'local' }\n"
  "    : { backend:'grok', model: (model.value||'').trim()||undefined };\n"
  "  const r = await fetch('/api/settings', {\n"
  "    method:'POST', headers:{'Content-Type':'application/json'},\n"
  "    body: JSON.stringify(body)\n"
  "  });\n"
  "  const j = await r.json();\n"
  "  if (!r.ok) { add('err', j.error||'settings failed'); return; }\n"
  "  add('s', 'Backend → '+j.backend+(j.base_url?' @ '+j.base_url:''));\n"
  "  await refreshAuth();\n"
  "}\n"
  "\n"
  "function startPoll(){\n"
  "  if (pollTimer) clearInterval(pollTimer);\n"
  "  waitEl.textContent = 'Waiting for browser approval…';\n"
  "  pollTimer = setInterval(async ()=>{\n"
  "    const ok = await refreshAuth();\n"
  "    if (ok && lastAuth && lastAuth.backend === 'grok' && lastAuth.signed_in) {\n"
  "      clearInterval(pollTimer); pollTimer = null;\n"
  "      waitEl.textContent = 'Connected.';\n"
  "      add('s', '✓ Grok session active.');\n"
  "    }\n"
  "  }, 2500);\n"
  "}\n"
  "\n"
  "async function connectGrok(){\n"
  "  add('s', 'Connect Grok: starting device login…');\n"
  "  showTab('settings');\n"
  "  await fetch('/api/settings', {\n"
  "    method:'POST', headers:{'Content-Type':'application/json'},\n"
  "    body: JSON.stringify({ backend:'grok' })\n"
  "  });\n"
  "  const r = await fetch('/api/auth/start', {\n"
  "    method:'POST', headers:{'Content-Type':'application/json'},\n"
  "    body: JSON.stringify({ force:true })\n"
  "  });\n"
  "  const j = await r.json();\n"
  "  if (!r.ok) { add('err', j.error||'connect failed'); return; }\n"
  "  if (j.signed_in) {\n"
  "    add('s', 'Already connected to Grok.');\n"
  "    authBox.classList.remove('show');\n"
  "    await refreshAuth();\n"
  "    return;\n"
  "  }\n"
  "  const u = j.verification_uri_complete || j.verification_uri || (location.origin+'/activate');\n"
  "  act.href = u;\n"
  "  act.textContent = u;\n"
  "  codeEl.textContent = j.user_code || '—';\n"
  "  authBox.classList.add('show');\n"
  "  be.value = 'grok';\n"
  "  syncLocalFields();\n"
  "  add('s', 'Open the activation link, approve, return here.');\n"
  "  startPoll();\n"
  "}\n"
  "\n"
  "async function send(){\n"
  "  let text = q.value.trim(); if (!text) return;\n"
  "  if (text === '/clear' || text === 'clear') { logEl.innerHTML=''; q.value=''; return; }\n"
  "  if (text === 'help' || text === '/help') {\n"
  "    add('s', 'help: Chat for prompts · Settings tab for backend & Connect Grok · @! shell · /s /log /clear');\n"
  "    q.value=''; return;\n"
  "  }\n"
  "  if (text === '/log') {\n"
  "    const r = await fetch('/api/log'); const j = await r.json();\n"
  "    add('s', j.log || '(empty)'); q.value=''; return;\n"
  "  }\n"
  "  if (text === '/s' || text === '/status') {\n"
  "    await refreshAuth(); showTab('settings'); q.value=''; return;\n"
  "  }\n"
  "  if (text === '/settings') { showTab('settings'); q.value=''; return; }\n"
  "  go.disabled = true;\n"
  "  add('u', '› '+text);\n"
  "  q.value = '';\n"
  "  try {\n"
  "    const r = await fetch('/api/chat', {\n"
  "      method:'POST', headers:{'Content-Type':'application/json'},\n"
  "      body: JSON.stringify({ prompt:text })\n"
  "    });\n"
  "    const j = await r.json();\n"
  "    if (j.need_login) {\n"
  "      add('s', j.error || 'Need Grok connect');\n"
  "      await connectGrok();\n"
  "    } else {\n"
  "      add('a', j.reply || j.error || '(no reply)');\n"
  "    }\n"
  "  } catch (e) {\n"
  "    add('err', 'error: '+e);\n"
  "  }\n"
  "  go.disabled = false;\n"
  "  q.focus();\n"
  "}\n"
  "\n"
  "$('btn-apply').onclick = () => applyBackend().catch(e => add('err', ''+e));\n"
  "$('btn-refresh').onclick = () => refreshAuth().catch(e => add('err', ''+e));\n"
  "$('btn-connect').onclick = () => connectGrok().catch(e => add('err', ''+e));\n"
  "$('btn-activate').onclick = () => { window.open('/activate', '_blank', 'noopener'); };\n"
  "go.onclick = send;\n"
  "q.addEventListener('keydown', e => {\n"
  "  if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); }\n"
  "  if (e.key === 'Escape') { q.focus(); q.select(); }\n"
  "});\n"
  "\n"
  "(async function boot(){\n"
  "  const ok = await refreshAuth();\n"
  "  if (ok) add('s', 'Ready. Use Chat, or open Settings for backend / Connect Grok.');\n"
  "  else {\n"
  "    add('s', 'Not connected. Open Settings → Connect Grok, or set Local for llama.cpp.');\n"
  "    showTab('settings');\n"
  "  }\n"
  "})();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
;
#endif
