#ifndef NANOBOT_WWW_INDEX_H
#define NANOBOT_WWW_INDEX_H
static const char WWW_INDEX_HTML[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "<meta charset=\"utf-8\"/>\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/>\n"
  "<title>nanobot</title>\n"
  "<style>\n"
  "  :root { color-scheme: dark; --bg:#0b0f12; --fg:#e8eef2; --acc:#00e5ff; --mut:#7a8a94; --line:#1c262c; --ok:#3ddc97; }\n"
  "  * { box-sizing: border-box; }\n"
  "  html,body { margin:0; height:100%; background:var(--bg); color:var(--fg);\n"
  "    font: 16px/1.35 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }\n"
  "  #wrap { display:flex; flex-direction:column; height:100%; max-width:52rem; margin:0 auto; padding:0.5rem; }\n"
  "  header { color:var(--mut); font-size:12px; letter-spacing:0.04em; padding:0.25rem 0 0.5rem;\n"
  "    border-bottom:1px solid var(--line); display:flex; justify-content:space-between; gap:0.5rem; }\n"
  "  header b { color:var(--acc); font-weight:600; }\n"
  "  #gate { flex:1; display:flex; flex-direction:column; justify-content:center; gap:1rem; padding:1rem 0; }\n"
  "  #gate h1 { font-size:1.1rem; margin:0; color:var(--fg); font-weight:600; }\n"
  "  #gate p { margin:0; color:var(--mut); font-size:14px; max-width:36rem; }\n"
  "  #act { display:inline-block; text-align:center; text-decoration:none; background:var(--acc); color:#00343a;\n"
  "    font-weight:700; padding:0.9rem 1.2rem; border-radius:8px; font-size:16px; }\n"
  "  #act:focus { outline:2px solid #fff; outline-offset:2px; }\n"
  "  #code { color:var(--acc); letter-spacing:0.12em; font-size:1.25rem; }\n"
  "  #log { flex:1; overflow:auto; white-space:pre-wrap; word-break:break-word; padding:0.75rem 0; font-size:14px; }\n"
  "  .u { color:var(--acc); } .a { color:var(--fg); } .s { color:var(--mut); }\n"
  "  #bar { display:flex; gap:0.4rem; border-top:1px solid var(--line); padding-top:0.5rem; }\n"
  "  #q { flex:1; min-width:0; background:#11181c; color:var(--fg); border:1px solid var(--line);\n"
  "    border-radius:6px; padding:0.7rem 0.75rem; font: inherit; outline:none; }\n"
  "  #q:focus { border-color:var(--acc); }\n"
  "  #go { background:var(--acc); color:#00343a; border:0; border-radius:6px; padding:0 1rem;\n"
  "    font: inherit; font-weight:700; cursor:pointer; min-width:4.5rem; }\n"
  "  #go:disabled { opacity:0.5; cursor:wait; }\n"
  "  #hint { font-size:11px; color:var(--mut); padding:0.35rem 0 0; }\n"
  "  #app { display:none; flex-direction:column; flex:1; min-height:0; }\n"
  "  #app.on { display:flex; }\n"
  "  #gate.off { display:none; }\n"
  "  .ok { color:var(--ok); }\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"wrap\">\n"
  "  <header><span><b>nanobot</b> · browser Grok session</span><span id=\"st\">…</span></header>\n"
  "\n"
  "  <div id=\"gate\">\n"
  "    <h1>Activate Grok session</h1>\n"
  "    <p>Open the link below on <b>BlackCube</b> in a browser where you use Grok.\n"
  "       It uses your normal browser login — no API keys.</p>\n"
  "    <p>Code: <span id=\"code\">—</span></p>\n"
  "    <a id=\"act\" href=\"#\" target=\"_blank\" rel=\"noopener\">Open activation link</a>\n"
  "    <p class=\"s\" id=\"wait\">Waiting for browser approval… this page updates automatically.</p>\n"
  "  </div>\n"
  "\n"
  "  <div id=\"app\">\n"
  "    <div id=\"log\" aria-live=\"polite\"></div>\n"
  "    <div id=\"bar\">\n"
  "      <input id=\"q\" type=\"text\" autocomplete=\"off\" autocorrect=\"off\" spellcheck=\"false\"\n"
  "        placeholder=\"one line → Enter…\" autofocus maxlength=\"2000\"/>\n"
  "      <button id=\"go\" type=\"button\">Go</button>\n"
  "    </div>\n"
  "    <div id=\"hint\">Titan2: type → Enter · @! shell · /s status · /log · /clear</div>\n"
  "  </div>\n"
  "</div>\n"
  "<script>\n"
  "const log = document.getElementById('log');\n"
  "const q = document.getElementById('q');\n"
  "const go = document.getElementById('go');\n"
  "const st = document.getElementById('st');\n"
  "const gate = document.getElementById('gate');\n"
  "const app = document.getElementById('app');\n"
  "const act = document.getElementById('act');\n"
  "const codeEl = document.getElementById('code');\n"
  "function add(cls, t){ const d=document.createElement('div'); d.className=cls; d.textContent=t; log.appendChild(d); log.scrollTop=log.scrollHeight; }\n"
  "function showApp(){ gate.classList.add('off'); app.classList.add('on'); q.focus(); }\n"
  "function showGate(){ gate.classList.remove('off'); app.classList.remove('on'); }\n"
  "\n"
  "async function refreshAuth(){\n"
  "  try {\n"
  "    const r = await fetch('/api/auth'); const j = await r.json();\n"
  "    if (j.signed_in) {\n"
  "      st.innerHTML = '<span class=\"ok\">session✓</span> · '+(j.model||'');\n"
  "      showApp();\n"
  "      return true;\n"
  "    }\n"
  "    st.textContent = 'need browser login';\n"
  "    showGate();\n"
  "    if (j.verification_uri_complete || j.verification_uri) {\n"
  "      const u = j.verification_uri_complete || j.verification_uri;\n"
  "      act.href = u;\n"
  "      act.textContent = 'Open activation link';\n"
  "    }\n"
  "    if (j.user_code) codeEl.textContent = j.user_code;\n"
  "    return false;\n"
  "  } catch(e){ st.textContent = 'offline'; return false; }\n"
  "}\n"
  "\n"
  "async function send(){\n"
  "  let text = q.value.trim(); if(!text) return;\n"
  "  if(text==='/clear'){ log.innerHTML=''; q.value=''; return; }\n"
  "  if(text==='/log'){\n"
  "    const r=await fetch('/api/log'); const j=await r.json(); add('s', j.log||'(empty)'); q.value=''; return;\n"
  "  }\n"
  "  if(text==='/s'||text==='/status'){ await refreshAuth(); q.value=''; return; }\n"
  "  go.disabled=true; add('u','› '+text); q.value='';\n"
  "  try {\n"
  "    const r = await fetch('/api/chat', { method:'POST', headers:{'Content-Type':'application/json'},\n"
  "      body: JSON.stringify({prompt:text}) });\n"
  "    const j = await r.json();\n"
  "    if (j.need_login) { add('s', j.error||'need login'); await refreshAuth(); }\n"
  "    else add('a', j.reply || j.error || '(no reply)');\n"
  "  } catch(e){ add('s','error: '+e); }\n"
  "  go.disabled=false; q.focus();\n"
  "}\n"
  "go.onclick = send;\n"
  "q.addEventListener('keydown', e => {\n"
  "  if(e.key==='Enter' && !e.shiftKey){ e.preventDefault(); send(); }\n"
  "  if(e.key==='Escape'){ q.focus(); q.select(); }\n"
  "});\n"
  "document.addEventListener('keydown', e => {\n"
  "  if(e.key==='/' && document.activeElement!==q && app.classList.contains('on')){ e.preventDefault(); q.focus(); }\n"
  "});\n"
  "\n"
  "(async function boot(){\n"
  "  const ok = await refreshAuth();\n"
  "  if (ok) add('s','Session active. One line in — shell tools run on the SSH host.');\n"
  "  else {\n"
  "    // ensure device login started\n"
  "    await fetch('/api/auth/start', {method:'POST'});\n"
  "    await refreshAuth();\n"
  "  }\n"
  "  setInterval(async ()=>{\n"
  "    if (!app.classList.contains('on')) {\n"
  "      const ok = await refreshAuth();\n"
  "      if (ok) add('s','✓ Grok session active. Type a command line.');\n"
  "    }\n"
  "  }, 3000);\n"
  "})();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
;
#endif
