#ifndef NANOBOT_WWW_INDEX_H
#define NANOBOT_WWW_INDEX_H
static const char WWW_INDEX_HTML[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "<meta charset=\"utf-8\"/>\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/>\n"
  "<title>nanobot</title>\n"
  "<style>\n"
  "  :root { color-scheme: dark; --bg:#0b0f12; --fg:#e8eef2; --acc:#00e5ff; --mut:#7a8a94; --line:#1c262c; --ok:#3ddc97; }\n"
  "  * { box-sizing: border-box; }\n"
  "  html,body { margin:0; height:100%; background:var(--bg); color:var(--fg);\n"
  "    font: 16px/1.35 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }\n"
  "  #wrap { display:flex; flex-direction:column; height:100%; max-width:52rem; margin:0 auto; padding:0.5rem; }\n"
  "  header { color:var(--mut); font-size:12px; letter-spacing:0.04em; padding:0.25rem 0 0.5rem;\n"
  "    border-bottom:1px solid var(--line); display:flex; justify-content:space-between; gap:0.5rem; flex-wrap:wrap; }\n"
  "  header b { color:var(--acc); font-weight:600; }\n"
  "  #gate { flex:1; display:flex; flex-direction:column; justify-content:center; gap:0.85rem; padding:1rem 0; }\n"
  "  #gate h1 { font-size:1.1rem; margin:0; color:var(--fg); font-weight:600; }\n"
  "  #gate p { margin:0; color:var(--mut); font-size:14px; max-width:36rem; }\n"
  "  #settings { border:1px solid var(--line); border-radius:8px; padding:0.75rem; display:flex; flex-direction:column; gap:0.5rem; max-width:28rem; }\n"
  "  #settings label { font-size:12px; color:var(--mut); }\n"
  "  #settings select, #settings input { width:100%; background:#11181c; color:var(--fg); border:1px solid var(--line);\n"
  "    border-radius:6px; padding:0.55rem 0.6rem; font: inherit; }\n"
  "  .row { display:flex; gap:0.5rem; flex-wrap:wrap; }\n"
  "  .btn { text-align:center; text-decoration:none; background:var(--acc); color:#00343a;\n"
  "    font-weight:700; padding:0.75rem 1rem; border-radius:8px; font-size:15px; border:0; cursor:pointer; font: inherit; }\n"
  "  .btn.sec { background:transparent; color:var(--acc); border:1px solid var(--acc); }\n"
  "  .btn:disabled { opacity:0.5; cursor:wait; }\n"
  "  #act { display:inline-block; }\n"
  "  #code { color:var(--acc); letter-spacing:0.12em; font-size:1.25rem; }\n"
  "  #log { flex:1; overflow:auto; white-space:pre-wrap; word-break:break-word; padding:0.75rem 0; font-size:14px; }\n"
  "  .u { color:var(--acc); } .a { color:var(--fg); } .s { color:var(--mut); }\n"
  "  #bar { display:flex; gap:0.4rem; border-top:1px solid var(--line); padding-top:0.5rem; }\n"
  "  #q { flex:1; min-width:0; background:#11181c; color:var(--fg); border:1px solid var(--line);\n"
  "    border-radius:6px; padding:0.7rem 0.75rem; font: inherit; outline:none; }\n"
  "  #q:focus { border-color:var(--acc); }\n"
  "  #go { background:var(--acc); color:#00343a; border:0; border-radius:6px; padding:0 1rem;\n"
  "    font: inherit; font-weight:700; cursor:pointer; min-width:4.5rem; }\n"
  "  #go:disabled { opacity:0.5; cursor:wait; }\n"
  "  #hint { font-size:11px; color:var(--mut); padding:0.35rem 0 0; }\n"
  "  #app { display:none; flex-direction:column; flex:1; min-height:0; }\n"
  "  #app.on { display:flex; }\n"
  "  #gate.off { display:none; }\n"
  "  .ok { color:var(--ok); }\n"
  "  #linkbox { font-size:12px; color:var(--mut); word-break:break-all; }\n"
  "  #linkbox a { color:var(--acc); }\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"wrap\">\n"
  "  <header>\n"
  "    <span><b>nanobot</b> · standalone outer host</span>\n"
  "    <span id=\"st\">…</span>\n"
  "  </header>\n"
  "\n"
  "  <div id=\"gate\">\n"
  "    <h1>Connect &amp; backend</h1>\n"
  "    <p>Select LLM backend. <b>Connect Grok</b> starts device-code auth and shows an\n"
  "       <code>http</code> activation link (browser login — no API keys).</p>\n"
  "\n"
  "    <div id=\"settings\">\n"
  "      <label for=\"backend\">Backend</label>\n"
  "      <select id=\"backend\">\n"
  "        <option value=\"grok\">Grok (cloud, browser auth)</option>\n"
  "        <option value=\"local\">Local / llama.cpp (OpenAI-compatible)</option>\n"
  "      </select>\n"
  "      <label for=\"base\">Local base URL (llama.cpp)</label>\n"
  "      <input id=\"base\" type=\"text\" placeholder=\"http://127.0.0.1:8080/v1\" value=\"http://127.0.0.1:8080/v1\"/>\n"
  "      <label for=\"model\">Model id</label>\n"
  "      <input id=\"model\" type=\"text\" placeholder=\"grok-4.5 or local model\" value=\"\"/>\n"
  "      <div class=\"row\">\n"
  "        <button class=\"btn sec\" type=\"button\" id=\"applyBackend\">Apply backend</button>\n"
  "        <button class=\"btn\" type=\"button\" id=\"connectGrok\">Connect Grok</button>\n"
  "      </div>\n"
  "    </div>\n"
  "\n"
  "    <p>Code: <span id=\"code\">—</span></p>\n"
  "    <a id=\"act\" class=\"btn\" href=\"#\" target=\"_blank\" rel=\"noopener\" style=\"display:none\">Open activation link</a>\n"
  "    <div id=\"linkbox\"></div>\n"
  "    <p class=\"s\" id=\"wait\">Waiting…</p>\n"
  "  </div>\n"
  "\n"
  "  <div id=\"app\">\n"
  "    <div class=\"row\" style=\"padding:0.4rem 0; gap:0.4rem;\">\n"
  "      <select id=\"backendApp\" style=\"background:#11181c;color:var(--fg);border:1px solid var(--line);border-radius:6px;padding:0.35rem;\">\n"
  "        <option value=\"grok\">Grok</option>\n"
  "        <option value=\"local\">llama.cpp / local</option>\n"
  "      </select>\n"
  "      <button class=\"btn sec\" type=\"button\" id=\"reconnect\" style=\"padding:0.35rem 0.7rem;font-size:13px\">Connect Grok</button>\n"
  "    </div>\n"
  "    <div id=\"log\" aria-live=\"polite\"></div>\n"
  "    <div id=\"bar\">\n"
  "      <input id=\"q\" type=\"text\" autocomplete=\"off\" autocorrect=\"off\" spellcheck=\"false\"\n"
  "        placeholder=\"one line → Enter…  (@! shell)\" autofocus maxlength=\"2000\"/>\n"
  "      <button id=\"go\" type=\"button\">Go</button>\n"
  "    </div>\n"
  "    <div id=\"hint\">@! shell · help · /s · /log · /clear · backend pluggable · not affiliated with xAI</div>\n"
  "  </div>\n"
  "</div>\n"
  "<script>\n"
  "const log = document.getElementById('log');\n"
  "const q = document.getElementById('q');\n"
  "const go = document.getElementById('go');\n"
  "const st = document.getElementById('st');\n"
  "const gate = document.getElementById('gate');\n"
  "const app = document.getElementById('app');\n"
  "const act = document.getElementById('act');\n"
  "const codeEl = document.getElementById('code');\n"
  "const waitEl = document.getElementById('wait');\n"
  "const linkbox = document.getElementById('linkbox');\n"
  "const backendSel = document.getElementById('backend');\n"
  "const backendApp = document.getElementById('backendApp');\n"
  "const baseIn = document.getElementById('base');\n"
  "const modelIn = document.getElementById('model');\n"
  "\n"
  "function add(cls, t){ const d=document.createElement('div'); d.className=cls; d.textContent=t; log.appendChild(d); log.scrollTop=log.scrollHeight; }\n"
  "function showApp(){ gate.classList.add('off'); app.classList.add('on'); q.focus(); }\n"
  "function showGate(){ gate.classList.remove('off'); app.classList.remove('on'); }\n"
  "\n"
  "function applyAuthUi(j){\n"
  "  if (j.backend === 'grok') { backendSel.value = 'grok'; backendApp.value = 'grok'; }\n"
  "  else { backendSel.value = 'local'; backendApp.value = 'local'; }\n"
  "  if (j.base_url && j.backend !== 'grok') baseIn.value = j.base_url;\n"
  "  if (j.model) modelIn.value = j.model;\n"
  "  const local = j.needs_browser === false || j.backend === 'openai_compatible';\n"
  "  if (j.signed_in || local) {\n"
  "    const tag = local ? 'local' : 'session✓';\n"
  "    st.innerHTML = '<span class=\"ok\">'+tag+'</span> · '+(j.model||'')+(j.backend?' · '+j.backend:'');\n"
  "    showApp();\n"
  "    return true;\n"
  "  }\n"
  "  st.textContent = 'need browser login';\n"
  "  showGate();\n"
  "  const u = j.verification_uri_complete || j.verification_uri;\n"
  "  if (u) {\n"
  "    act.href = u;\n"
  "    act.style.display = 'inline-block';\n"
  "    act.textContent = 'Open activation link';\n"
  "    linkbox.innerHTML = 'Link: <a href=\"'+u+'\" target=\"_blank\" rel=\"noopener\">'+u+'</a>';\n"
  "  }\n"
  "  if (j.user_code) codeEl.textContent = j.user_code;\n"
  "  waitEl.textContent = 'Waiting for browser approval…';\n"
  "  return false;\n"
  "}\n"
  "\n"
  "async function refreshAuth(){\n"
  "  try {\n"
  "    const r = await fetch('/api/auth'); const j = await r.json();\n"
  "    return applyAuthUi(j);\n"
  "  } catch(e){ st.textContent = 'offline'; return false; }\n"
  "}\n"
  "\n"
  "async function applyBackend(fromApp){\n"
  "  const b = (fromApp ? backendApp : backendSel).value;\n"
  "  const body = b === 'local'\n"
  "    ? { backend:'local', base_url: baseIn.value || 'http://127.0.0.1:8080/v1', model: modelIn.value || 'local' }\n"
  "    : { backend:'grok', model: modelIn.value || undefined };\n"
  "  const r = await fetch('/api/settings', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(body) });\n"
  "  const j = await r.json();\n"
  "  if (!j.ok) { waitEl.textContent = j.error || 'backend failed'; return j; }\n"
  "  waitEl.textContent = 'Backend: ' + j.backend + (j.base_url ? ' @ '+j.base_url : '');\n"
  "  await refreshAuth();\n"
  "  return j;\n"
  "}\n"
  "\n"
  "async function connectGrok(){\n"
  "  waitEl.textContent = 'Starting Grok device login…';\n"
  "  await applyBackend(false);\n"
  "  // force grok backend then start auth\n"
  "  await fetch('/api/settings', { method:'POST', headers:{'Content-Type':'application/json'},\n"
  "    body: JSON.stringify({ backend:'grok', model: modelIn.value || undefined }) });\n"
  "  const r = await fetch('/api/auth/start', { method:'POST' });\n"
  "  const j = await r.json();\n"
  "  if (j.signed_in) { waitEl.textContent = 'Already signed in'; await refreshAuth(); return; }\n"
  "  const u = j.verification_uri_complete || j.verification_uri || (location.origin + '/activate');\n"
  "  // Prefer full device URI; also show local activate redirect\n"
  "  const localAct = location.origin + '/activate';\n"
  "  act.href = u;\n"
  "  act.style.display = 'inline-block';\n"
  "  act.textContent = 'Open activation link';\n"
  "  codeEl.textContent = j.user_code || '—';\n"
  "  linkbox.innerHTML =\n"
  "    'Authorize: <a href=\"'+u+'\" target=\"_blank\" rel=\"noopener\">'+u+'</a><br/>'+\n"
  "    'Or open: <a href=\"'+localAct+'\" target=\"_blank\" rel=\"noopener\">'+localAct+'</a> (nanobot redirects to Grok)';\n"
  "  waitEl.textContent = 'Open the link, approve in browser, this page will unlock.';\n"
  "  showGate();\n"
  "}\n"
  "\n"
  "document.getElementById('applyBackend').onclick = () => applyBackend(false);\n"
  "document.getElementById('connectGrok').onclick = connectGrok;\n"
  "document.getElementById('reconnect').onclick = connectGrok;\n"
  "backendApp.onchange = () => applyBackend(true);\n"
  "\n"
  "async function send(){\n"
  "  let text = q.value.trim(); if(!text) return;\n"
  "  if(text==='/clear'){ log.innerHTML=''; q.value=''; return; }\n"
  "  if(text==='help'||text==='/help'){ add('s','@! cmd · /s status · /log · /clear · Connect Grok button · backend Grok|local'); q.value=''; return; }\n"
  "  if(text==='/log'){\n"
  "    const r=await fetch('/api/log'); const j=await r.json(); add('s', j.log||'(empty)'); q.value=''; return;\n"
  "  }\n"
  "  if(text==='/s'||text==='/status'){ await refreshAuth(); q.value=''; return; }\n"
  "  go.disabled=true; add('u','› '+text); q.value='';\n"
  "  try {\n"
  "    const r = await fetch('/api/chat', { method:'POST', headers:{'Content-Type':'application/json'},\n"
  "      body: JSON.stringify({prompt:text}) });\n"
  "    const j = await r.json();\n"
  "    if (j.need_login) { add('s', j.error||'need login — use Connect Grok'); showGate(); await connectGrok(); }\n"
  "    else add('a', j.reply || j.error || '(no reply)');\n"
  "  } catch(e){ add('s','error: '+e); }\n"
  "  go.disabled=false; q.focus();\n"
  "}\n"
  "go.onclick = send;\n"
  "q.addEventListener('keydown', e => {\n"
  "  if(e.key==='Enter' && !e.shiftKey){ e.preventDefault(); send(); }\n"
  "  if(e.key==='Escape'){ q.focus(); q.select(); }\n"
  "});\n"
  "\n"
  "(async function boot(){\n"
  "  const ok = await refreshAuth();\n"
  "  if (ok) add('s','Ready. Backend selectable; Connect Grok generates http activation link.');\n"
  "  else {\n"
  "    waitEl.textContent = 'Pick backend, or Connect Grok for browser authorize.';\n"
  "  }\n"
  "  setInterval(async ()=>{\n"
  "    if (!app.classList.contains('on')) {\n"
  "      const ok = await refreshAuth();\n"
  "      if (ok) add('s','✓ Session active. Type a command line.');\n"
  "    }\n"
  "  }, 3000);\n"
  "})();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
;
#endif
