if(NOT DEFINED NANOBOT_COMPILER_LOADED)
  set(NANOBOT_COMPILER_LOADED ON)
  add_compile_options(-Wall -Wextra -Wno-unused-parameter)
  # feature macros for POSIX APIs; safe on Linux/BSD/macOS
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_compile_definitions(_GNU_SOURCE)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    add_compile_definitions(_DARWIN_C_SOURCE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "BSD")
    add_compile_definitions(_BSD_SOURCE)
  else()
    add_compile_definitions(_DEFAULT_SOURCE)
  endif()
endif()
